### PR TITLE
Add CUDA 9.1 wheel

### PR DESCRIPTION
**Pull request by kmaehashi**
Support `cupy-cuda91` wheel.

### CODE REVIEW

**Comment by mitmul** [comment]
LGTM. How do you usually test a wheel? Do I need to check if it works correctly with this coming environment settings locally?

**Comment by mitmul** [comment]
Ah, the verification procedures are explained in the README. I’ll try it and then merge.

**Comment by kmaehashi** [comment]
Thank you for taking your time for review!
You need to run `dist.py` for 2 times; first for building a wheel, second to verify.
Build runs on CentOS 6 docker container, and verification runs [smoke tests](https://github.com/cupy/cupy-release-tools/tree/master/release-tests) on each systems listed in `verify_systems` (`['ubuntu16.04']`).

**Comment by mitmul** [comment]
LGTM. I confirmed the building of wheel succeeds and verified the deliverable by the `dist.py` tool.
What I did is shown below.

Preparation:
- Download `nccl_2.1.4-1+cuda9.1_x86_64.txz` from NVIDIA site and put it into `~/nccl_assets` dir on the test server

Build check:
```
$ ./dist.py \
--action build \
--target wheel-linux \
--nccl-assets ~/nccl_assets \
--python 3.6.0 \
--cuda 9.1 \
--source ~/cupy
```
Then I got `cupy_cuda91-4.0.0b4-cp36-cp36m-manylinux1_x86_64.whl`,

Verification:
```
$ ./dist.py \
--action verify \
--target wheel-linux \
--nccl-assets ~/nccl_assets \
--python 3.6.0 \
--cuda 9.1 \
--dist cupy_cuda91-4.0.0b4-cp36-cp36m-manylinux1_x86_64.whl \
--test release-tests/common \
--test release-tests/cudnn \
--test release-tests/nccl
```

**Pull request merged**
