### PR TITLE
Support CUDA 11.4

### PR DESCRIPTION
**Pull request by takagi**
Blocked by https://github.com/cupy/cupy/pull/5434.

### CODE REVIEW

**Comment by takagi** [comment]
Is it okay to leave the line for 11.2?
https://github.com/cupy/cupy-release-tools/blob/ec2eb8f21d8394282f7c629ceafd1df1dc8fcb01/.pfnci/config.pbtxt#L60

**Comment by kmaehashi** [comment]
> Is it okay to leave the line for 11.2?

Yes. (Actually, this `command` won't be used anywhere)

**Comment by kmaehashi** [comment]
I've installed CUDA 11.4 on FlexCI Windows instance.
/test

**Pull request merged**
