### PR TITLE
Fix description for ROCm packages

### LINKED ISSUE #74: Dedicated description for ROCm packages
https://pypi.org/project/cupy-rocm-4-0/#description

Currently, it links to CUDA Toolkit download page 😅

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #74, also adds `cupy-rocm-4-0` to the list of packages.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Test passed!

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
