### PR TITLE
Support ROCm 5.0

### PR DESCRIPTION
**Pull request by takagi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Let's use 5.0.1 image (it seems not ready yet):
https://hub.docker.com/r/rocm/dev-centos-7/tags?page=1&name=5.0

**Comment by takagi** [comment]
Changed to use ROCm 5.0 images as 5.0.1 images are not still available and the next release date (2022-03-31 for v11.0.0b1) is approaching.

**Comment by kmaehashi** [comment]
Will merge after `cupy-release-tools.linux.rocm` pass

**Pull request merged**
