### PR TITLE
Bump cuDNN version to v8.1.0

### PR DESCRIPTION
**Pull request by takagi**

### CODE REVIEW

**Comment by takagi** [comment]
Looks https://github.com/cupy/cupy/pull/4558/commits/c1c68a2a6fa3967511ad2c148daf2a7db3e28c64 breaks the case the compute capability of the GPU is higher than that of the CUDA Toolkit supports.

**Comment by leofang** [comment]
> Looks [cupy/cupy@c1c68a2](https://github.com/cupy/cupy/commit/c1c68a2a6fa3967511ad2c148daf2a7db3e28c64) breaks the case the compute capability of the GPU is higher than that of the CUDA Toolkit supports.

Interesting. Shouldn't this always be an error anyway? For example, one should not expect to run Ampere on CUDA 10.x.

**Comment by takagi** [comment]
No, but it's the case our CI fails here. You mean the test should be fixed as opposed to taking care of that in CuPy?

**Comment by takagi** [comment]
Blocked by https://github.com/cupy/cupy/pull/4682.

**Comment by leofang** [comment]
> No, but it's the case our CI fails here. You mean the test should be fixed as opposed to taking care of that in CuPy?

Sorry I dropped the ball here. I don't have good answers for that, so I think it's reasonable to partially revert cupy/cupy@c1c68a2 as being done in cupy/cupy#4682. 

Perhaps, to address cupy/cupy#4660 we could try detecting unsupported GPUs (w.r.t. the current CUDA version), for those either too old or too new?

**Comment by kmaehashi** [comment]
To address https://github.com/cupy/cupy/issues/4660 we need to maintain a list of supported archs for each CUDA version (https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) AND if the current device CC is not in the list, use the fallback one.

**Comment by leofang** [comment]
> To address [cupy/cupy#4660](https://github.com/cupy/cupy/issues/4660) we need to maintain a list of supported archs for each CUDA version (https://docs.nvidia.com/cuda/nvrtc/index.html#group__options) AND if the current device CC is not in the list, use the fallback one.

Yeah if we're on CUDA 11.2+, our life could be much simpler as NVRTC provides this list for us via the new `nvrtcGetSupportedArchs` API.

**Comment by kmaehashi** [comment]
Nice, I wasn't aware of that API 😃

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
@kmaehashi Would you merge this if looks fine?

**Pull request merged**
