### PR TITLE
Fix cuda_lib directory missing in sdist build

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Testing: https://ci.preferred.jp/cupy-wheel-linux/70396/

**Comment by kmaehashi** [comment]
Testing: https://ci.preferred.jp/r/job/70433

**Comment by kmaehashi** [comment]
Testing: https://ci.preferred.jp/r/job/70436

**Comment by kmaehashi** [comment]
Testing: https://ci.preferred.jp/cupy-wheel-linux/70441/

**Comment by kmaehashi** [comment]
Manual test passed.

/test

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
