### PR TITLE
Bump base images for verification

### PR DESCRIPTION
**Pull request by kmaehashi**
xref cupy/cupy#7682

### CODE REVIEW

**Comment by kmaehashi** [comment]
#352 needs to be merged first

**Comment by emcastillo** [comment]
1.0s
--
00:28:41.772453 STDERR 1392] | #3 ERROR: docker.io/nvidia/cuda:12.1.1-runtime-ubuntu18.04: not found

1.0s
[00:28:41.772453 STDERR 1392]](https://ci.preferred.jp/cupy-release-tools/136730/#L6687)	#3 ERROR: docker.io/nvidia/cuda:12.1.1-runtime-ubuntu18.04: not found

**Comment by kmaehashi** [comment]
Thanks, it seems CUDA 12.1.1 no longer provides Docker images on Ubuntu 18.04.

/test

**Pull request merged**
